;Included file
;���Ƃ͒ʏ�ʂ�ݒ�ł��܂�

DanResult_Rank=195,570

DanResult_StatePanel=0,0
DanResult_Exam=365,458

DanResult_Perfect=1228,186
DanResult_Good=1228,250
DanResult_Miss=1228,315
DanResult_Roll=1632,186
DanResult_MaxCombo=1632,250
DanResult_TotalHit=1632,315
DanResult_Score=898,219

DanResult_SongPanel_Main_X=391,391,391
DanResult_SongPanel_Main_Y=114,424,734

DanResult_Sections_Perfect_X=645,645,645
DanResult_Sections_Perfect_Y=359,669,979
DanResult_Sections_Good_X=1001,1001,1001
DanResult_Sections_Good_Y=359,669,979
DanResult_Sections_Miss_X=1357,1357,1357
DanResult_Sections_Miss_Y=359,669,979
DanResult_Sections_Roll_X=1713,1713,1713
DanResult_Sections_Roll_Y=359,669,979

DanResult_DanTitles_X=407,407,407
DanResult_DanTitles_Y=142,452,762
DanResult_DanIcon_X=455,455,455
DanResult_DanIcon_Y=283,593,903
DanResult_Difficulty_Cymbol_X=545,545,545
DanResult_Difficulty_Cymbol_Y=261,571,881
DanResult_Level_Number_X=555,555,555
DanResult_Level_Number_Y=276,586,896

DanResult_Font_DanTitles_Size=36