;Included file
;���Ƃ͒ʏ�ʂ�ݒ�ł��܂�
; TJAPlayer3-Develop-ReWrite�Œǉ�����SkinConfig

Game_UIMove_4P=0,264
Game_UIMove_5P=0,216

; Notes
Game_SENotes_Offset_4P=-3,150
Game_SENotes_Offset_5P=-3,141
Game_ScrollField_4P=523,69
Game_ScrollField_5P=523,40

; Judge
Game_Judge_4P=550,40
Game_Judge_5P=550,30

; Rank
Game_ScoreRank_4P=130,132
Game_ScoreRank_5P=130,120

; 4_CourseSymbol
Game_CourseSymbol_4P=-6,84
Game_CourseSymbol_5P=-6,72
Game_CourseSymbol_Back_4P=1344,70
Game_CourseSymbol_Back_5P=1344,58
Game_CourseSymbol_Back_Rect_4P=0,192,576,193
Game_CourseSymbol_Back_Rect_5P=0,210,576,157
        
; 6_Taiko
Game_Score_4P=55,81
Game_Score_5P=55,69
Game_Score_Add_4P=55,129
Game_Score_Add_5P=55,129
Game_Score_AddBonus_4P=55,189
Game_Score_AddBonus_5P=55,189
Game_Taiko_Background_4P=0,12
Game_Taiko_Background_5P=0,0
Game_Taiko_ModIcons_4P=122,90
Game_Taiko_ModIcons_5P=122,72
Game_Taiko_NamePlate_4P=0,182
Game_Taiko_NamePlate_5P=0,152
Game_Taiko_PlayerNumber_4P=6,85
Game_Taiko_PlayerNumber_5P=6,73
Game_Taiko_4P=307,45
Game_Taiko_5P=307,15
Game_Taiko_Combo_4P=400,140
Game_Taiko_Combo_5P=400,110
Game_Taiko_Combo_Ex_4P=400,140
Game_Taiko_Combo_Ex_5P=400,110
Game_Taiko_Combo_Ex4_4P=400,140
Game_Taiko_Combo_Ex4_5P=400,110
Game_Taiko_Combo_Text_4P=399,185
Game_Taiko_Combo_Text_5P=399,155
Game_Taiko_Frame_4P=499,12
Game_Taiko_Frame_5P=499,0
        
; 7_Gauge
Game_Gauge_4P=766,-5
Game_Gauge_5P=766,-17
Gauge_Soul_4P=1802,-18
Gauge_Soul_5P=1802,-30
Gauge_Soul_Fire_4P=1668,-127
Gauge_Soul_Fire_5P=1668,-139

; 10_Effects
Game_Effects_Hit_Explosion_4P=523,69
Game_Effects_Hit_Explosion_5P=523,40
Game_Effect_Fire_4P=523,69
Game_Effect_Fire_5P=523,40
        
; 11_Balloon
Game_Balloon_Balloon_4P=566,-48
Game_Balloon_Balloon_5P=566,-77
Game_Balloon_Balloon_Frame_4P=573,-18
Game_Balloon_Balloon_Frame_5P=573,-6
Game_Balloon_Balloon_Number_4P=550,100
Game_Balloon_Balloon_Number_5P=550,100

; 12_Lane
Game_Lane_4P=499,69
Game_Lane_5P=499,58

; PuchiChara
Game_PuchiChara_4P=345,243
Game_PuchiChara_5P=345,225
