;Included file
;���Ƃ͒ʏ�ʂ�ݒ�ł��܂�
; TJAPlayer3-Develop-ReWrite�Œǉ�����SkinConfig

TowerResult_ScoreRankEffect=965,618

TowerResult_Toutatsu=440,245
TowerResult_MaxFloors=910,415

TowerResult_Ten=1405,728
TowerResult_Score=950,728

TowerResult_CurrentFloor=950,395
TowerResult_ScoreCount=1455,728
TowerResult_RemainingLifes=965,728

TowerResult_Gauge_Soul=430,703

TowerResult_Font_TowerText=32
TowerResult_Font_TowerText48=72
TowerResult_Font_TowerText72=72